# version: '3.7'

services:
  ##################################
  # Backing Services 
  ##################################
  # MongoDB backing service (single node replica set)
  mongodb:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    extra_hosts:
      - "mongodb:127.0.0.1"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

  ##################################
  # Elasticsearch backing service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "xpack.security.enabled=false"
      - "action.destructive_requires_name=false"
      - "network.bind_host=0.0.0.0"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  ##################################
  # Kibana for Elasticsearch service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: c69548d9027afcf4d55146b1d425a9f4c69548d9027afcf4d55146b1d425a9f4

  ##################################
  # Zookeeper manager for Kafka cluster
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"

  ##################################
  # Kafka event bus
  kafka:
    image: confluentinc/cp-kafka:7.3.0  
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:19092
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      - zookeeper

  ##################################
  # Kafka Connector (Custom connector with Mongo and Elastic plugins)
  kafka-connect:
    image: ghcr.io/agile-learning-institute/mentorhub-kafka-connect:latest
    ports:
      - "9093:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_GROUP_ID: "mongo-elastic-sync"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    depends_on:
      kafka:
        condition: service_started
      initialize-mongodb:
        condition: service_completed_successfully
      initialize-elasticsearch:
        condition: service_completed_successfully

  ##################################
  # Backing Service Configuration Utilities
  ##################################
  # Initialize MongoDB and load test data
  initialize-mongodb:
    image: ghcr.io/agile-learning-institute/mentorhub-msm:latest
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017/?replicaSet=rs0
      - LOAD_TEST_DATA=true
      - DB_NAME=mentorHub

  ##################################
  # Initialize Elasticsearch and load test data
  initialize-elasticsearch:
    image: ghcr.io/agile-learning-institute/mentorhub-elasticsearch:latest
    environment:
      CLIENT_OPTIONS: '{"node":"http://elasticsearch:9200"}'
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
      LOAD_TEST_DATA: true
    depends_on:
      initialize-mongodb:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_healthy
